A little bit of help on the refactor/tilemap-rewrite branch
Trouv/bevy_ecs_ldtk pull request #104
Opened 2022-08-07 04:16 UTC by nfagerlund

I moved the Bevy dependency to 0.8 and the bevy_ecs_tilemap one to 0.7, then started looking for whatever broke. 

This isn't a complete upgrade and it isn't in proper working condition (the examples still need a Heron bump that isn't out yet, and also I'm still trying to untangle whatever's going on with inherited visibility), but it IS building. And all these changes seem to be things you'd have needed to do anyway, so maybe it'll save you a couple steps.

2022-08-07 04:40 UTC, Trouv commented
Yeah this is all good. I can merge it now, unless you want to make any more changes

2022-08-07 05:26 UTC, nfagerlund commented
@Trouv go for it! 🤘🏼 I’m still dinking with some stuff to see if I can figure out the visibility thing, but that wouldn’t prompt me to reconsider any of what’s already in here.

2022-08-07 07:36 UTC, Zak0749 requested changes
For the from_grid_with_padding calls I think it might be better to take in the tileset_definintion padding element ,which would allow tile maps with padding, rather than using a static zero

```

TextureAtlas::from_grid_with_padding(
                tileset.clone(),
                Vec2::new(tile.w as f32, tile.h as f32),
                tileset_definition.c_wid as usize,
                tileset_definition.c_hei as usize,
                Vec2::splat(tileset_definition.spacing as f32),
                Vec2::splat(tileset_definition.padding as f32),
)
```

But other than that it looks good 👍

2022-08-08 00:46 UTC, nfagerlund commented
I think I chased down the rest of the visibility inheritance business, and got the `basic` example rendering properly! 

<details><summary>Before / after screenshots</summary>
**Before:** (main @ 8a56caf)
![Screen Shot 2022-08-07 at 5 27 25 PM](https://user-images.githubusercontent.com/484309/183317813-8148bdaf-d248-467b-a8f2-6d9bf3d9fd05.png)

**After:**
![Screen Shot 2022-08-07 at 5 28 02 PM](https://user-images.githubusercontent.com/484309/183317854-90606b63-e218-4197-847b-6897980fb973.png)
</details>

I threw bevy-inspector-egui in there temporarily to spy on the hierarchy (when I was chasing the visibility around), and that looks to be the same too. The main difference is that, at least in debug mode, the entity sprite assets seem to pop-in somewhat later in this branch than they used to on main. 

Next step for me is to see if I can continue working on my toy project with this branch; if so, I'll probably leave the rest of the upgrade and cleanup to you! (If I get blocked there, maybe I'll add more commits. 😹)

2022-08-08 01:23 UTC, nfagerlund commented
Update: totally seems to work correctly in my toy project. 🙌🏼

2022-08-08 04:04 UTC, Trouv commented
This looks good, and the new hierarchy-related changes fixed some bugs I was dealing with before you picked this up. Thanks so much!

@Zak0749 That's a good point. I'll merge this now but I'll keep that in mind while I keep working on the update

2022-08-08 04:04 UTC, merged