With attribute
Trouv/bevy_ecs_ldtk pull request #128
Opened 2022-11-08 18:43 UTC by marcoseiza

# Summary

Adds a new attribute to the `LdtkEntity` derive macro named `with`. It allows for bundles to implement custom initializers using a method. This macro takes in a scoped function with signature `(e: EntityInstance) -> T` where T is the field type.

# Example

```rs
pub struct Bundle {
   #[with(foo_initializer)]
    foo: i32;
}

fn foo_initializer(_e: EntityInstance) -> i32 {
    4
}
```

<details>
  <summary>Longer Example</summary>
  
```rs
#[derive(Clone, Default, Bundle)]
pub struct ColliderBundle {
    pub collider: Collider,
    pub rigid_body: RigidBody,
    pub damping: Damping,
    ...
}

#[derive(Bundle, Default, LdtkEntity)]
pub struct PlayerBundle {
    player: Player,
    #[with(player_collider)]
    #[bundle]
    collider: ColliderBundle,
}

fn player_collider(_: EntityInstance) -> ColliderBundle {
    ColliderBundle {
        collider: Collider::capsule(Vec2::new(0., -4.), Vec2::new(0., -12.), 5.),
        rigid_body: RigidBody::Dynamic,
        rotation_constraints: LockedAxes::ROTATION_LOCKED,
        damping: Damping {
            linear_damping: 10.0,
            ..Default::default()
        },
        ..Default::default()
    }
}
```
</details>

# Issue

The same functionality can be done using `from_entity_instance` by filtering the `identifier` to the correct type. However, this could cause function bloat when many entities with different identifiers implement the same bundle. You can have cleaner and safer code separation with this `with(function)` attribute.

# ToDo

- [ ] Ensure type safety of function return; the error messages aren't very good if the function doesn't return the correct type

2022-11-12 04:09 UTC, Trouv requested changes
Thanks for the contribution. This is a great idea, and in hindsight it seems so obvious. Def wanna get this in.

2022-11-12 04:09 UTC, Trouv commented on macros/src/ldtk_entity.rs
> +        }
```suggestion
        let with = field
            .attrs
            .iter()
            .find(|a| *a.path.get_ident().as_ref().unwrap() == WITH_ATTRIBUTE_NAME);
        if let Some(attribute) = with {
            field_constructions.push(expand_with_attribute(attribute, field_name, field_type));
            continue;
        }
```

2022-11-12 04:10 UTC, Trouv commented
Please add some documentation w/ an example to `src/app/ldtk_entity.rs`

2022-11-12 22:50 UTC, marcoseiza commented on macros/src/ldtk_entity.rs
> +        }
updated!

2022-11-12 22:51 UTC, marcoseiza commented
Ready for another review!

2022-11-13 01:09 UTC, Trouv requested changes

2022-11-13 01:16 UTC, marcoseiza commented on src/app/ldtk_entity.rs
> +/// }
Updated to pass test

2022-11-13 01:17 UTC, marcoseiza commented
Checked with `cargo test` and `cargo build`, all pass!

2022-11-13 01:22 UTC, Trouv requested changes

2022-11-13 01:22 UTC, Trouv commented on src/app/ldtk_entity.rs
> +///
You can hide the boring stuff from the docs by preceding the lines with `# `:
```suggestion
/// # use bevy::prelude::*;
/// # use bevy_ecs_ldtk::prelude::*;
/// # #[derive(Component, Default)]
/// # pub struct Player;
/// # #[derive(Component, Default, Clone)]
/// # pub struct Money(f32);
```

2022-11-13 01:23 UTC, marcoseiza commented on src/app/ldtk_entity.rs
> +///
oh! I thought it was an error in the suggestion, that's really cool. Updating now

2022-11-13 01:25 UTC, marcoseiza commented
okay, third times the charm  😅

2022-11-13 01:26 UTC, Trouv commented on src/app/ldtk_entity.rs
> +///
Yeah! in case you don't know you can always view it to make sure it looks good with `cargo doc --open`

2022-11-13 01:28 UTC, Trouv approved these changes

2022-11-13 01:34 UTC, merged

2022-11-13 01:35 UTC, marcoseiza commented
Thanks @Trouv for reviewing!!