Migrated to bevy 0.9
Trouv/bevy_ecs_ldtk pull request #138
Opened 2022-11-17 19:51 UTC by greenfierydragon

Does not apply to the platformer example (rapier2d) because we are waiting on https://github.com/dimforge/bevy_rapier/pull/272. When that PR is merged I will update this.

2022-11-18 01:31 UTC, Trouv requested changes
Thanks for the contribution!

2022-11-18 01:31 UTC, Trouv commented on src/resources.rs
> +use bevy::prelude::{CoreStage, GlobalTransform, Resource};
This `#[allow(unused_imports)]` import was originally intended for imports that aren't used by in code but *are* referenced by the docs. Little did I know that rust-doc doesn't actually link those up properly anyway. Since we now actually use an item from `prelude` in this module, can we update it to be `use bevy::prelude::*;` and remove the `#[allow(unused_imports)]`?

2022-11-18 01:31 UTC, Trouv commented on src/utils.rs
> +                Some(Vec2::splat(tileset_definition.padding as f32)),
This change to `TextureAtlas` needs to be updated in at least one more place, line 232 of `macros/src/ldtk_entity.rs`. Feel free to just wrap `Some` around the padding and offset values without changing the macro itself in that case.

2022-11-18 01:32 UTC, Trouv commented
> When that PR is merged I will update this.

Feel free to depend on that PR in main. I'm also down to update that example in a separate PR if it's a lot of changes.

2022-11-18 13:12 UTC, johanhelsing commented
Not sure if it's this PR, or an existing bevy_ecs_ldtk issue, but I have problems with the background and tiles not lining up:

![image](https://user-images.githubusercontent.com/2620557/202712663-53528362-7066-424b-a081-ac8089ca66ee.png)

The white box is the background for the level with the sunnyland grass textures, so either the positions of the background or the tiles is off.

![image](https://user-images.githubusercontent.com/2620557/202713005-9574b754-4c17-4967-9050-1b7767dde5f2.png)

2022-11-18 16:30 UTC, Trouv commented
> I have problems with the background and tiles not lining up:

This should be fixed by #136, this PR hasn't pulled from main since that was merged

2022-11-18 20:47 UTC, greenfierydragon commented on src/resources.rs
> +use bevy::prelude::{CoreStage, GlobalTransform, Resource};
Am I correct in saying this to be done across all files?

2022-11-18 20:51 UTC, Trouv commented on src/resources.rs
> +use bevy::prelude::{CoreStage, GlobalTransform, Resource};
Nah just this one is fine since this is the only one being updated in this PR. The others are a bit unrelated to the purpose of this PR and can be changed later

2022-11-19 09:27 UTC, greenfierydragon commented on src/utils.rs
> +                Some(Vec2::splat(tileset_definition.padding as f32)),
Resolves in 222a46f

2022-11-19 09:39 UTC, greenfierydragon commented
> I think
> 
> ```rust
> app.add_plugin(bevy_ecs_tilemap::TilemapPlugin)
> ```
> 
> should probably be removed from `LdtkPlugin::build`. If more than one plugins does this, the user will get panics like:
> 
> ```
> thread 'main' panicked at 'Error adding plugin bevy_ecs_tilemap::TilemapPlugin: : plugin was already added in application', C:\Users\Johan\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.9.0\src\app.rs:841:63
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Alternatively, put it behind a `app.is_plugin_added` check.

Fixed in 90092d8

2022-11-19 09:46 UTC, greenfierydragon commented
Rebased based of upstream

2022-11-19 11:17 UTC, johanhelsing reviewed
Alignment issues gone :)

No other issues

2022-11-19 11:17 UTC, johanhelsing commented on Cargo.toml
> +bevy_rapier2d = { git = "https://github.com/devil-ira/bevy_rapier.git", branch = "bevy-0.9" }
v0.19.0 is out now :)

2022-11-19 13:09 UTC, greenfierydragon commented on Cargo.toml
> +bevy_rapier2d = { git = "https://github.com/devil-ira/bevy_rapier.git", branch = "bevy-0.9" }
Should be there now!

2022-11-19 17:35 UTC, Trouv commented
Pushing a formatting change...

2022-11-19 17:47 UTC, Trouv approved these changes
LGTM. Thanks for your hard work @greenfierydragon and @johanhelsing - I really appreciate it

2022-11-19 17:48 UTC, merged