Allow opting out of SpriteSheetBundle grid construction
Trouv/bevy_ecs_ldtk pull request #161
Opened 2023-01-27 14:08 UTC by geieredgar

This is an attempt to fix #105 and #151.

This adds an optional `no_grid` argument to the `#[sprite_sheet_bundle]` attribute. Instead of using `TextureAtlas::from_grid`, a `TextureAtlas` with a single sprite will be used.  

Instead of using `#[sprite_sheet_bundle(no_grid)]`, a field of type `NoGridSpriteSheetBundle` annotated with the `#[ldtk_entity]` attribute can be used.

2023-02-07 03:56 UTC, Trouv requested changes
Thanks for the contribution, I see now that it would be difficult to support these offset rectangles of tiles with grids.

2023-02-07 03:56 UTC, Trouv commented on src/components.rs
> +pub struct NoGridSpriteSheetBundle {
I think the addition of this bundle is a bit unnecessary. I'm happy with just the `#[sprite_sheet_bundle(no_grid)]` attribute

2023-02-07 03:56 UTC, Trouv commented on src/app/ldtk_entity.rs
> +/// /// - `#[sprite_sheet_bundle(no_grid)]` will create the field using information from the LDtk Editor visual,
```suggestion
/// - `#[sprite_sheet_bundle(no_grid)]` will create the field using information from the LDtk Editor visual,
```

2023-02-07 03:56 UTC, Trouv commented on src/app/ldtk_entity.rs
> +/// if it has one, but without using a grid. Instead a single texture will be used.
Could we add something along the lines of "This may be useful if the LDtk entity's visual uses a rectangle of tiles from its tileset, but will prevent using the generated TextureAtlas for animation purposes."

2023-02-07 23:35 UTC, geieredgar commented on src/components.rs
> +pub struct NoGridSpriteSheetBundle {
Ok, I removed everything related to `NoGridSpriteSheetBundle`.

2023-02-07 23:36 UTC, geieredgar commented on src/app/ldtk_entity.rs
> +/// if it has one, but without using a grid. Instead a single texture will be used.
Done.

2023-02-07 23:37 UTC, geieredgar commented on src/app/ldtk_entity.rs
> +/// /// - `#[sprite_sheet_bundle(no_grid)]` will create the field using information from the LDtk Editor visual,
Fixed.

2023-02-08 12:29 UTC, geieredgar commented on examples/basic.rs
> +}
OK, I've restored the basic example and updated the platformer example instead.

2023-02-09 02:34 UTC, Trouv approved these changes
LGTM, thanks again

2023-02-09 02:37 UTC, merged