Document feature flags in crate-level docs
Trouv/bevy_ecs_ldtk pull request #164
Opened 2023-02-08 14:57 UTC by geieredgar

Fixes #163.

2023-02-09 04:35 UTC, Trouv requested changes

2023-02-09 04:35 UTC, Trouv commented on src/lib.rs
> +//! to work on Tile and AutoTile layers.
this is also required for wasm

2023-02-09 11:00 UTC, geieredgar commented on src/lib.rs
> +//! to work on Tile and AutoTile layers.
OK, added.

2023-02-10 00:54 UTC, Trouv approved these changes

2023-02-10 00:55 UTC, merged