Update to bevy `0.10`
Trouv/bevy_ecs_ldtk pull request #168
Opened 2023-03-06 21:04 UTC by geieredgar

Currently blocked by

- [ ] https://github.com/StarArawn/bevy_ecs_tilemap/pull/390
- [ ] https://github.com/dimforge/bevy_rapier/pull/324
- [ ] https://github.com/dimforge/nalgebra/pull/1213

2023-03-11 05:01 UTC, Trouv requested changes
Thanks for your hard work updating this and `bevy_ecs_tilemap`. It really made my already-busy week so much easier

2023-03-11 05:18 UTC, Trouv requested changes

2023-03-11 05:18 UTC, Trouv commented on src/lib.rs
> +                    .after(CoreSet::Update)
I think technically this should come after `CoreSet::UpdateFlush`, since that's where the post-`Update` `apply_system_buffers` lives. `apply_level_selection` and, less importantly, `worldly_adoption` both need this buffer to minimize update-delay for users

2023-03-11 10:57 UTC, geieredgar commented on src/lib.rs
>      /// [StageLabel] for stages added by the plugin.
Done.

2023-03-11 10:58 UTC, geieredgar commented on src/lib.rs
> +            .add_system(systems::clean_respawn_entities.in_base_set(LdtkSystemSet::PostProcessApi))
You are right, there was an `apply_system_buffers` missing.

2023-03-11 10:58 UTC, geieredgar commented on src/lib.rs
> +                    .after(CoreSet::Update)
Done.

2023-03-11 11:01 UTC, geieredgar commented on src/lib.rs
> +        PostProcessApi,
This sounds good, so I implemented the nested set idea. I've added a new non-base system set type `InternalSystemSet`. I've decided to make it non-pub, because I think this type mainly encodes implementation details, so leaving it out of the public API allows non-breaking changes. I would like to hear your feedback about that.

2023-03-11 11:05 UTC, geieredgar commented
I've addressed all of the requested changes. Unfortunately, I've encountered what I believe is some race condition between systems of `bevy_ecs_ldtk` and `bevy_rapier` in the `platformer` example. I've experienced them before, but hoped this was an issue with the then WIP `bevy_rapier` update. I will investigate them later today.

2023-03-11 18:32 UTC, Trouv commented on src/lib.rs
> +                    .in_set(InternalSystemSet::PreClean),
I think you can just `.configure_set(InternalSystemSet::PreClean.in_base_set(LdtkSystemSet::ProcessApi))`, and then you don't need to specify `.in_base_set(LdtkSystemSet::ProcessApi)` on the systems in `PreClean`

2023-03-11 18:32 UTC, Trouv commented on src/lib.rs
> +    enum InternalSystemSet {
Do you think we could name this something like `ProcessApiSet`? Since it's only going to be used in `ProcessApi`

2023-03-11 18:32 UTC, Trouv commented on src/lib.rs
> +        PostProcessApi,
Yeah keeping it private is fine. If somebody feels like they need it they can file an issue in the future, but I don't expect that to happen. Actually, I feel like this plugin has too many public items as it is

2023-03-11 18:53 UTC, geieredgar commented on src/lib.rs
> +                    .in_set(InternalSystemSet::PreClean),
Ok, I also added a `Clean` set and used that to order the systems, so that we can do `.in_set(ProcessApiSet::Clean)` instead of `.in_base_set(LdtkSystemSet::ProcessApi).after(ProcessApiSet::Clean)`.

2023-03-11 18:53 UTC, geieredgar commented on src/lib.rs
> +    enum InternalSystemSet {
Done.

2023-03-11 19:29 UTC, geieredgar commented
Here are my investigation results about the race condition in the `platformer` example:

Without any explicit ordering between `LdtkSystemSet::ProcessApi` and `PhysicsSet::SyncBackend`, the platformer example quite often crashes at startup with the following error:
```
thread 'main' panicked at 'error[B0003]: Could not insert a bundle (of type `bevy_rapier2d::dynamics::rigid_body::RapierRigidBodyHandle`) for entity 3814v0 because it doesn't exist in this World.
```

The system that issues the command to insert the bundle is `init_rigid_bodies` which is part of the `PhysicsSet::SyncBackend` set.

Even if the example does not crash, the player is sometimes spawned at the wrong position, see

![Wrong spawn position](https://user-images.githubusercontent.com/7457961/224506817-114cbd4e-335b-42bd-9250-4ff941851695.png)

Ordering `PhysicsSet::SyncBackend` before `LdtkSystemSet::ProcessApi` didn't crash anymore, but the wrong spawn position did also happen occasionally (like about 1 of 30 times). Sometimes the player didn't spawn at all (maybe it was only invisible/occluded by the level), see

![Player didn't spawn](https://user-images.githubusercontent.com/7457961/224506980-b1f2ed5c-9fbf-41f5-9fee-c7668b01c5c1.png)

Therefore, I changed the `platformer` example to explicitly schedule `PhysicsSet::SyncBackend` after `LdtkSystemSet::ProcessApi`. With this I didn't encounter any crashes or wrong spawn positions, but this doesn't prove it cannot happen.

### Side note

As a side note, I've run the `platformer` example in release mode and looked at the first few frames using renderdoc. The frames looked the same between all configurations but there was a difference to the current `main` branch: In the `main` branch, the first frame was completely gray, the second completely blue. With the updates, the first three frames looked like this:


Frame 1:
![Frame 1](https://user-images.githubusercontent.com/7457961/224507637-2814b200-d86e-4d22-9679-4b16cffeef74.png)
Frame 2:
![Frame 2](https://user-images.githubusercontent.com/7457961/224507645-072d0953-773b-453b-9892-756c5311ca85.png)
Frame 3:
![Frame 3](https://user-images.githubusercontent.com/7457961/224507651-d9c4abc7-aabc-4100-8f07-23ed05fd58b4.png)

In `main` the "Frame 2" was often the third frame, sometimes "Frame 1" was the third frame, followed by "Frame 2".

I believe that this is related to #140.

2023-03-11 19:36 UTC, Trouv commented on examples/platformer/main.rs
> +        .configure_set(LdtkSystemSet::ProcessApi.before(PhysicsSet::SyncBackend))
If this fixes the issue you observed we should probably leave a comment here explaining why it's necessary, and also mention it in the docs for `LdtkSystemSet::ProcessApi`

2023-03-11 19:45 UTC, Trouv commented
I see, it makes sense that we'd have to be explicit in the ordering of our systems vs rapiers now. I'm guessing with this explicit scheduling that the issue is truly gone, but it's hard to be sure. It's a bit of a shame to require users to do that - but I'm also okay with it for now. I think we could keep `0.6` focused on faithfully recreating the old schedule, and then later make more serious changes to the schedule with this issue and #140 in mind.

2023-03-11 20:00 UTC, geieredgar commented
Yeah, I believe this is something `bevy_ecs`'s ambiguity checker should be able to catch, but I think it is currently disabled by default because of the many false positives it reports. Improvements there might change that, so the user is at least warned about the race conditions. But this still leaves the question open which systems should run first, so I think it is important to document that somewhere. 

Another solution might be to add a `bevy_rapier` feature that adds the schedule constraint automatically in `LdtkPlugin::build`.

2023-03-11 20:08 UTC, geieredgar commented on examples/platformer/main.rs
> +        .configure_set(LdtkSystemSet::ProcessApi.before(PhysicsSet::SyncBackend))
Added comments. Not sure if the `LdtkSystemSet::ProcessApi` comment is what you had in mind.

2023-03-11 22:59 UTC, Trouv commented
> Another solution might be to add a `bevy_rapier` feature that adds the scheduling constraint automatically in `LdtkPlugin::build`.

Hmm, I think this could be cool if we had more integration with `bevy_rapier` as part of such a feature. For example, more `LdtkEntity` attribute macros for collisions, or something. My gut reaction to this is that users will see that feature listed and expect it to be more in depth than one scheduling constraint.

I think making users responsible for the scheduling constraint is fine for now but I definitely want to announce it in the release and have it documented somewhere like you've already done. I'm interested in reworking the scheduling a bit after this release anyway, so the requirement may disappear at that point

2023-03-11 22:59 UTC, Trouv commented on examples/platformer/main.rs
> +        .configure_set(LdtkSystemSet::ProcessApi.before(PhysicsSet::SyncBackend))
I'd say explicitly mention `bevy_rapier` as an example since it's a common integration

2023-03-12 09:01 UTC, geieredgar commented on examples/platformer/main.rs
> +        .configure_set(LdtkSystemSet::ProcessApi.before(PhysicsSet::SyncBackend))
Done.

2023-03-12 21:27 UTC, Trouv reviewed
A few more small things

2023-03-12 21:27 UTC, Trouv commented on src/lib.rs
>          /// In particular, this stage processes..
```suggestion
        /// In particular, this set processes..
```

2023-03-12 21:27 UTC, Trouv commented on src/lib.rs
> +    pub enum LdtkSystemSet {
Now that it's more likely users will have to import this, could you export it in the prelude? After doing so we won't need to import it separately in the platformer example

2023-03-12 21:27 UTC, Trouv commented on src/lib.rs
> +        /// [CoreSet::Update].
A similar `CoreStage` > `CoreSet` change needs to happen for the docs of `resources::LevelEvent::Transformed`

2023-03-12 22:28 UTC, geieredgar commented on src/lib.rs
> +    pub enum LdtkSystemSet {
Done.

2023-03-12 22:29 UTC, geieredgar commented on src/lib.rs
> +        /// [CoreSet::Update].
Done.

2023-03-14 21:27 UTC, Trouv approved these changes
LGTM - I think I will merge this now just so people can depend on the main branch of the main repo rather than yours. We can fix the dependency once bevy_ecs_tilemap is updated.

2023-03-14 21:28 UTC, merged