feat: add `EntityIid` component which is added to all entities by default
Trouv/bevy_ecs_ldtk pull request #194
Opened 2023-06-08 13:49 UTC by adtennant

This is a first step on the road to having an easy way of looking up entity information from `LdtkAsset`.

**Question**
Should it be possible to disable this using `LdtkSettings`? I'm not sure it's worth worrying about as the memory usage should be minimal as the IID are always GUIDs.

2023-06-17 16:13 UTC, Trouv requested changes

2023-06-17 16:13 UTC, Trouv commented on src/components.rs
> +pub struct EntityIid(Cow<'static, str>);
I'm not that experienced with the `Cow` pointer, but since the internal value here isn't pub and we only provide immutable access to it, I'm not sure what the benefit is of using it? I'm not saying there isn't one, just curious what the thought process was here

2023-06-17 16:13 UTC, Trouv commented on src/components.rs
> +}
I know this violates the current organization of the repository, but I'd like to reorganize things soon(tm) into smaller modules. Do you think you could put all of this `EntityIid` stuff into its own module?

2023-06-17 16:16 UTC, Trouv commented
> * Should it be possible to disable this using `LdtkSettings`? I'm not sure it's worth worrying about as the memory usage should be minimal as the IID are always GUIDs. Perhaps a feature?

I think the `LdtkIndexer` stuff I mentioned makes sense to go behind a feature, but this `EntityIid` is small enough and generally-useful-enough that I think it's fine to make it non-optional.

> * Should this be a newtype? It makes sense to me and I can't see any reason for it to ever gain fields, but the other components within the crate all have named fields.

That's fine - I was pretty allergic to newtypes when I first wrote this plugin but no longer.

> * Should the `EntityIid` also carry its `Handle<LdtkAsset>`? I don’t think so personally as `LevelSelection` doesn’t have this concept.

I agree, it doesn't need it.

2023-06-17 17:34 UTC, adtennant commented on src/components.rs
> +pub struct EntityIid(Cow<'static, str>);
Mostly I was following the lead of [bevy](https://docs.rs/bevy/latest/bevy/index.html)::[core](https://docs.rs/bevy/latest/bevy/core/index.html)::[Name](https://docs.rs/bevy/latest/bevy/core/struct.Name.html#) as I see these being very similar (https://github.com/bevyengine/bevy/blob/main/crates/bevy_core/src/name.rs). 

There probably isn't a ton of benefit to it although it does make all the conversions and `new` trivial to implement.

2023-06-17 17:44 UTC, adtennant commented
@Trouv I've refactored `components.rs` into a folder, as I assume given time you'll want to break it down fully. It seemed neater than having `entity_iid.rs` floating around on its own.

2023-06-17 18:59 UTC, Trouv requested changes

2023-06-17 18:59 UTC, Trouv commented on src/components/entity_iid.rs
> +#[derive(Clone, Debug, Default, Deref, DerefMut, Hash, Eq, PartialEq, Component, Reflect)]
I prefer to not provide mutable access to the internal type here 
```suggestion
#[derive(Clone, Debug, Default, Deref, Hash, Eq, PartialEq, Component, Reflect)]
```

2023-06-17 18:59 UTC, Trouv commented on src/components.rs
> +pub struct EntityIid(Cow<'static, str>);
I see. Well if it's good enough for bevy, it's good enough for me

2023-06-17 20:07 UTC, Trouv requested changes
Sorry to be pedantic - I'd like the public items to have doc-strings

2023-06-17 20:07 UTC, Trouv commented on src/components/entity_iid.rs
> +    pub fn as_str(&self) -> &str {
```suggestion
    /// Returns the internal entity iid as a `&str`.
    #[inline(always)]
    pub fn as_str(&self) -> &str {
```

2023-06-17 20:07 UTC, Trouv commented on src/components/entity_iid.rs
> +    pub fn new(iid: impl Into<Cow<'static, str>>) -> Self {
```suggestion
    /// Construct an [`EntityIid`].
    pub fn new(iid: impl Into<Cow<'static, str>>) -> Self {
```

2023-06-17 20:25 UTC, Trouv requested changes
The `field_instances` example should probably be updated to take advantage of this in `mother.rs`

2023-06-17 20:53 UTC, adtennant commented
No worries about being pedantic, that is the point of doing code reviews 👍

2023-06-18 16:42 UTC, Trouv approved these changes
LGTM, thanks again

2023-06-18 16:42 UTC, merged