feat: add `get_entity_instance` to `LdtkAsset`
Trouv/bevy_ecs_ldtk pull request #195
Opened 2023-06-08 20:11 UTC by adtennant

This builds on the work in https://github.com/Trouv/bevy_ecs_ldtk/pull/194. I've split into two PRs in order to keep discussion focused, and because I think https://github.com/Trouv/bevy_ecs_ldtk/pull/194 in isolation still gives some benefits if this PR takes a little longer to get over the line. Unfortunately I can only set the base branch to one which exists in this repo (rather than my fork) so the diff includes all the other changes for now.

I went down this route rather than creating a `SystemParam` as discussed in https://github.com/Trouv/bevy_ecs_ldtk/pull/192 as it felt more natural for it to live alongside `get_level` and it massively simplifies the implementation.

I'm going to give some thought to how this can be extended to enable https://github.com/Trouv/bevy_ecs_ldtk/issues/70 as that is closely related to my actual use-case.

**Questions**
* Should the `traitless` example be updated to use this? Full trait less will still work the same, but with this you can mix both approaches. It removes a potential footgun.

2023-06-17 20:28 UTC, Trouv commented
> I went down this route rather than creating a SystemParam as discussed in https://github.com/Trouv/bevy_ecs_ldtk/pull/192 as it felt more natural for it to live alongside get_level and it massively simplifies the implementation.

Hmm I see what you mean. 

> I'm going to give some thought to how this can be extended to enable https://github.com/Trouv/bevy_ecs_ldtk/issues/70 as that is closely related to my actual use-case.

Yeah, editing the asset data is a no-no, and the spawned `Entity`s for an ldtk world naturally changes as the levels load/unload. I think, going with the approach you've laid out here, having a separate feature where we map `EntityIid`s to `Entity`s in a resource makes sense. `Option<Entity>` didn't really feel like it totally fit in `EntityIndices` when I originally suggested it anyway.

> * Should the `traitless` example be updated to use this? Full trait less will still work the same, but with this you can mix both approaches. It removes a potential footgun.

I think using this in an example is a good idea, but I'm fine with leaving that for a future PR. I'm not sure if `traitless` is the right one to update - its intention is to basically be a `--no-default-features` version of the `basic` example.

2023-06-18 16:54 UTC, adtennant commented
@Trouv I’ll rebase this in top of `main` tomorrow now that https://github.com/Trouv/bevy_ecs_ldtk/pull/194 is merged.

Do you have any feedback specific to these changes that needs addressing? Or would you rather make until there is a clean diff and discuss further?

2023-06-18 17:34 UTC, Trouv requested changes
This almost works, but unfortunately I forgot about external level files. I recommend reading my last comment first as addressing that probably changes things more fundamentally.

2023-06-18 17:34 UTC, Trouv commented on src/assets.rs
> +    }
I would like there to be separate methods for getting a reference to the layer instance and the level as well. It's okay to keep this PR small without them - but if they could depend on each other somehow then it might make sense to implement them all here and it would probably be an ideal implementation.

However, I think it's not quite that simple because we want these methods to accept an `&EntityIid` not an `&EntityIndexes`. So - if we had `get_entity_instance` use `get_layer_for_entity` internally, which in turn uses `get_level_for_entity` internally, we'd actually be looking up the same value in `EntityIndex` 3 times. I guess that's not that big of a deal though because the lookup is constant.

2023-06-18 17:34 UTC, Trouv commented on src/assets.rs
> +    /// Find a particular entity instance using an [EntityIid].
It's kind of obvious, but we should explain what a `None` (or as suggested in my next comment, `Err`) result means.

2023-06-18 17:34 UTC, Trouv commented on src/assets.rs
> +    pub fn get_entity_instance(&self, entity_iid: &EntityIid) -> Option<&EntityInstance> {
I wonder if returning `Result` w/ a custom error would be more clear. As opposed to a lookup in a `HashMap` where there are plenty of use cases that users would perform some logic in a `None` result, I think here users are more likely to be expecting this entity to exist.

A simple thiserror `NoSuchEntity` tuple-struct would suffice in the `Err` variant:
```rust
#[derive(Debug, Error)]
#[error("provided entity iid doesn't exist in the ldtk asset's index: {0}")]
struct NoSuchEntity(EntityIid);
```

I believe this is the only error we should be worried about. We should be able to `.expect()` the indexing of levels, layers, and entities if an `EntityIndexes` exists. The logic for creating that map is all private and should be correct

2023-06-18 17:34 UTC, Trouv commented on src/assets.rs
> +    pub entity_index: EntityIndex,
As mentioned in #192, I think it makes sense to put this field (and the types it depends on) behind a default `"index"` feature.

2023-06-18 17:34 UTC, Trouv commented on src/assets.rs
> +                    if let Some(layer_instances) = level.layer_instances.as_ref() {
Ah, - here's a bit of a snag in the implementation. These layers won't exist when LDtk is set to use external level files. They'll only exist on the `LdtkLevel` asset in that case. So, the entity index will be completely empty for users using external levels.

For context - if the user is not using external level files - those `LdtkLevel` assets *will* still exist and they'll be set as "labeled" assets of the `LdtkAsset`. If the user is using external level files - those `LdtkLevel` assets will be loaded separately as "dependent" assets of the `LdtkAsset`. Either way - the `Handle<LdtkLevel>` gets stored on the `LdtkAsset::level_map`.

I think we can only access the level data from this function in the "internal" case, unfortunately. In the external case, I believe the level data is loaded completely asynchronously to this function - and we can't await on it.

I think to have this feature work in both cases - we'll need access to both `LdtkAsset` data *and* `LdtkLevel` data - which I believe means we'll need to perform this logic during systems that access `Assets<LdtkAsset>` and `Assets<LdtkLevel>`, which is bringing me back to the `SystemParam` idea. Though, if you have another idea, or I'm missing something about bevy's asset system that allows us to do it here, I'm happy to hear it.

2023-06-19 10:29 UTC, adtennant commented on src/assets.rs
> +                    if let Some(layer_instances) = level.layer_instances.as_ref() {
Ah, yes. 

Is another potential solution to address this in documentation in the same way `get_level` works, or would you rather jump all the way to the most robust solution?

We'd need to provide some way of looking up within the `LdtkLevel` as well if we went down the documentation route.

The above comes from a slightly selfish place in that whilst the more robust (likely `SystemParam`) solution is probably better for the plugin longer term, I only need the more niave solution for my needs. I'm still happy to keep this moving, but if I can unblock my main project sooner that's obviously better for me - although there's nothing stopping me using a private fork for now to solve that.

2023-06-19 10:30 UTC, adtennant commented
Bumping this back to draft whilst we resolve what this should look like, @Trouv would you prefer me to create an issue to discuss this?

2023-06-21 02:52 UTC, Trouv commented on src/assets.rs
> +                    if let Some(layer_instances) = level.layer_instances.as_ref() {
Hmm my thought here is - is the naive solution a partial implementation of the full solution? Like is it something we can build on top of for future releases or is it something we'd like to replace in future releases? The way I imagine things working, I think it would be the latter, which makes me hesitant to merge.

Now what might be a good partial implementation would be to have a map of entityiids to layer/entity indexes for a specific level generated as a new field on an `LdtkLevel`. So, the same strategy you've implemented here but smaller in scope. I think then generating a resource mapping `EntityIid`s to `Handle<LdtkLevel>`s could build naturally on top of that, and a `SystemParam` providing a convenient API could build on top of that. I'm not sure if that first step would be very useful to you?

2023-06-21 03:07 UTC, Trouv commented on src/assets.rs
> +    pub fn get_entity_instance(&self, entity_iid: &EntityIid) -> Option<&EntityInstance> {
I see - I'm okay with that, this was a light suggestion anyway. Though the 2nd part of this suggestion makes me wonder - is it useful to `.expect()` something expected where a simple `?` is compatible? Probably slightly for catching bugs but not a big deal

2023-10-18 02:19 UTC, Trouv commented
> Bumping this back to draft whilst we resolve what this should look like, @Trouv would you prefer me to create an issue to discuss this?

I've been reworking the asset types and this should be a little bit easier now. I finally created an issue for this and am closing this PR in favor of it: #251. Thanks again, @adtennant

2023-10-18 02:19 UTC, closed without merging