feat: `#[bevy_ecs_ldtk(use_default_impl)]`
Trouv/bevy_ecs_ldtk pull request #222
Opened 2023-08-19 17:06 UTC by elenakrittik

Adds a new struct-level attribute `#[bevy_ecs_ldtk(use_default_impl)]` to `LdtkEntity` and `LdtkIntCell` derive macros.
When used, it changes the default behavior to populate fields that were not marked otherwise (i.e., those fields without any attributes on them)
from struct's `Default` impl. This way:
- Backwards compatibility is preserved.
- Users of this new attribute can still leverage convenience attributes like `#[sprite_bundle("...")]`.

This feature can be useful primarily in one way: when you have large bundles or a lot of bundles with external (from other crates) components on them,
it quickly becomes tedious and repetitive to write `#[with(...)]` callbacks for each attribute. With this attribute, you can move all logic into a single `impl Default`. This also solves #119 by allowing to easily switch behavior to the one most people usually expect.

[x] I have properly formatted code using `cargo fmt`.
[x] I have tested the code and documentation i changed by both crafting and running an example and by running `cargo test`.
[x] I have ran `cargo clippy` and fixed any issues arising from my changes.

2023-08-19 18:43 UTC, Trouv reviewed
It may be better to just make this the normal behavior, not opt-in or opt-out. It's certainly more flexible to make it opt-in like this, but I think the current behavior is a little confusing and it would be fine to just get rid of it. Making this the only behavior would also be a bit easier to maintain/test in the future, rather than having one more toggle-like feature to worry about. Also, I've been considering actually scaling back the macro functionality in future releases (not soon, like 0.11 or something), and if that comes to pass the opt-inness of this would probably be on the chopping block anyway.

Down side would be that it's a breaking change, but I'm not too worried about that. This library is far from stable, and I'm planning to release 0.9 with many breaking changes with plenty of time before bevy 0.12 comes out so people can upgrade at their own pace. Thoughts?

2023-08-19 18:55 UTC, elenakrittik commented
I personally totally share your vision and if breaking changes are for the better, then i'll make them. But at the same time i recognize that there's a plenty of developers with busy schedules and that they would rather prefer to receive bug fixes without the accompanying breaking changes. Though, in case of Bevy's ecosystem, i'm imagine most people will be fine with breaking changes, or pin bevy-related dependencies to specific versions and upgrade only when they're ready. I'll change this PR a bit later.

2023-08-19 20:43 UTC, elenakrittik commented
Done. Due to removal of backwards compatibility had to add lots of `#[derive(Default)]`s.

2023-08-20 17:25 UTC, Trouv requested changes
Thanks for making the breaking change, I think it's a bit better this way

2023-08-20 17:25 UTC, Trouv commented on macros/src/ldtk_entity.rs
> -        });
Do you think it would be a good idea to make it so the `..Default::default()` is only added if there are any remaining fields? That would make so technically `LdtkEntity` and `LdtkIntCell` bundles don't *have* to implement default, so long as all their fields are constructed by some other method, so a little more flexible. However, I could also see that just being a little bit confusing.

2023-08-20 17:25 UTC, Trouv commented on examples/basic.rs
> +#[derive(Default, Bundle, LdtkEntity)]
Do you think you could make this change in the `README.md` as well?

2023-08-20 17:25 UTC, Trouv commented on src/app/ldtk_entity.rs
>  ///     b: ComponentB,
On line 63, the docs say 
```rust
/// By default, each component or nested bundle in the bundle will be created using their [Default]
/// implementations.
```
It's a bit ambiguous but I think it's trying to describe the old behavior. I think we could make this a little more clear now by saying something like `By default, the fields of the bundle will be created using its [Default] implementation.`

2023-08-20 17:25 UTC, Trouv commented on src/app/ldtk_int_cell.rs
>  ///     b: ComponentB,
Same comment about the docs on line 59

2023-09-16 18:40 UTC, elenakrittik commented on macros/src/ldtk_entity.rs
> -        });
Not worth it IMHO. Hopefully made the docs clear enough.

2023-09-16 18:40 UTC, elenakrittik commented on src/app/ldtk_int_cell.rs
>  ///     b: ComponentB,
8527b03

2023-09-16 18:40 UTC, elenakrittik commented on src/app/ldtk_entity.rs
>  ///     b: ComponentB,
8527b03

2023-09-16 18:40 UTC, elenakrittik commented on examples/basic.rs
> +#[derive(Default, Bundle, LdtkEntity)]
8527b03

2023-09-16 18:57 UTC, elenakrittik commented on macros/src/ldtk_entity.rs
> -        });
Huh, seems latest clippy will force us to do this. Although i can't reproduce it locally.

2023-09-16 19:02 UTC, Trouv commented on macros/src/ldtk_entity.rs
> -        });
That or you can just allow the clippy lint in the macro. Either way is fine with me

2023-09-17 16:43 UTC, elenakrittik commented on macros/src/ldtk_entity.rs
> -        });
2cbcbbe

2023-09-17 16:44 UTC, elenakrittik commented
Done, sorry for this simple change taking so long.

2023-09-18 01:37 UTC, Trouv approved these changes
> Done, sorry for this simple change taking so long.

No worries. We're all volunteers here. Thanks again for the contribution!

2023-09-18 01:39 UTC, merged