Normalize resolved asset paths using `path_clean`.
Trouv/bevy_ecs_ldtk pull request #255
Opened 2023-10-21 15:37 UTC by focustense

Makes all paths relative to the `assets` root. Ensures that LDtk-linked assets are shared with assets loaded by `AssetServer`, [bevy_asset_loader](https://github.com/NiklasEi/bevy_asset_loader) and so on, as long as normalized paths are used for those (as they typically are), especially when the LDtk project is in a subdirectory.

Fixes #240

2023-10-21 23:34 UTC, focustense commented
The failing test looks like a platform-specificity issue; the native `Path` must treat the backslash as just a regular character, so `path_clean` ignores it too. I'll look into fix tomorrow - probably just make that test case Windows-conditional.

2023-10-24 01:34 UTC, Trouv requested changes

2023-10-24 01:34 UTC, Trouv commented on src/assets/ldtk_project.rs
> +    fn normalizes_windows_asset_paths() {
This isn't decorated w/ `#[test]` so I don't think it would run on windows either.

I'm also okay leaving this test out entirely, the CI does not build on windows and neither do I so it would be completely invisible in future reviews.

2023-10-24 03:50 UTC, focustense commented on src/assets/ldtk_project.rs
> +    fn normalizes_windows_asset_paths() {
Derp, rookie mistake there. Added the attribute, it still runs and passes fine - on my machine, anyway.

Maybe there's a chance it'll get stale under current maintenance conditions, but I think it's better to keep the test anyway. This code rarely seems to change, and _someone_ will eventually notice if it breaks on Windows and if so, the test will tell them why.

If it's important to you that the test be removed then let me know and I can do that. Otherwise, should be resolved.

2023-10-24 05:45 UTC, Trouv approved these changes
LGTM. Thanks for the suggestion and the tests as well

2023-10-24 05:46 UTC, merged