Don't set level selection if the level isn't loaded yet
Trouv/bevy_ecs_ldtk pull request #281
Opened 2023-12-14 01:57 UTC by MScottMcBee

Fixes #232 

Added a check so that when applying `LevelSelection`, there's a check to make sure the external level is loaded.

Works for my game and all tests pass, not sure if this has any weird knock-on effects.

2023-12-21 04:10 UTC, Trouv requested changes
Thanks for the contribution and for following up on this issue. I see why the change in the 0.12 branch doesn't fix this now.

2023-12-21 04:10 UTC, Trouv commented on src/systems.rs
> +                    }
So I believe the way this currently works is that `apply_level_set` wraps everything in a `if let Some(project)` for the `LdtkProject`, which acts as a check that the project is loaded. We don't actually listen for `AssetEvent::Created` or `AssetEvent::LoadedWithDependencies` for this. This of course does *not* act as a check that levels are loaded, just that the project is loaded, which is the bug. I think you should be able to use the new [`AssetServer::get_recursive_dependency_load_state`](https://docs.rs/bevy/latest/bevy/asset/struct.AssetServer.html#method.get_recursive_dependency_load_state) method for a more correct check that the project (and its dependencies) are loaded.

2024-01-20 06:47 UTC, MScottMcBee commented
Thanks for the feedback and sorry for the long response time. I switched over to use `get_recursive_dependency_load_state` and wow is that a lot cleaner.

2024-01-20 23:27 UTC, Trouv approved these changes
Seems good. Will merge this *after* `feat/bevy-0.12` so that the squash commit credits you properly.

2024-01-31 00:15 UTC, merged