Bevy 0.13 support
Trouv/bevy_ecs_ldtk pull request #302
Opened 2024-02-21 23:20 UTC by theshortcut

Leaving this in draft until https://github.com/StarArawn/bevy_ecs_tilemap/pull/508 merges.

Most of the changes here are related to the new `TextureAtlasLayout` and the examples in the repo look correct to me still at least.

2024-03-02 17:45 UTC, neocturne commented
I've updated my project to use this branch, and I haven't noticed any issues :tada: 
(besides having to add a number of manual `LdtkEntity` impls to work around #305, but that is unrelated to this PR)

2024-03-13 09:05 UTC, linonetwo commented
Hi @theshortcut , https://github.com/StarArawn/bevy_ecs_tilemap/pull/508 is merged.

2024-03-13 10:35 UTC, linonetwo commented
Get some error when using

```toml
bevy = "0.13.0"
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap" }
bevy_ecs_ldtk = { git = "https://github.com/theshortcut/bevy_ecs_ldtk/", branch = "bevy-0.13" }
```


```rs
% cargo check
    Checking bevy_ecs_ldtk v0.9.0 (https://github.com/theshortcut/bevy_ecs_ldtk/?branch=bevy-0.13#ef466f3a)
error[E0308]: mismatched types
   --> /Users/linonetwo/.cargo/git/checkouts/bevy_ecs_ldtk-a845ef6482ca980f/ef466f3/src/tile_makers.rs:210:17
    |
209 |               color: TileColor(
    |                      --------- arguments to this struct are incorrect
210 | /                 *color_map
211 | |                     .get(&value)
212 | |                     .expect("Int grid values should have an associated IntGridValueDefinition"),
    | |_______________________________________________________________________________________________^ expected `bevy_render::color::Color`, found `bevy::prelude::Color`
    |
    = note: `bevy::prelude::Color` and `bevy_render::color::Color` have similar names, but are actually distinct types
note: `bevy::prelude::Color` is defined in crate `bevy_render`
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_render-0.13.0/src/color/mod.rs:13:1
    |
13  | pub enum Color {
    | ^^^^^^^^^^^^^^
note: `bevy_render::color::Color` is defined in crate `bevy_render`
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_render-0.12.1/src/color/mod.rs:13:1
    |
13  | pub enum Color {
    | ^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `bevy_render` are being used?
note: tuple struct defined here
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_ecs_tilemap-0.12.0/src/tiles/mod.rs:76:12
    |
76  | pub struct TileColor(pub Color);
    |            ^^^^^^^^^

error[E0277]: the trait bound `TileBundle: bevy::prelude::Component` is not satisfied
   --> /Users/linonetwo/.cargo/git/checkouts/bevy_ecs_ldtk-a845ef6482ca980f/ef466f3/src/components/mod.rs:313:22
    |
313 |     pub tile_bundle: TileBundle,
    |                      ^^^^^^^^^^ the trait `bevy::prelude::Component` is not implemented for `TileBundle`
    |
    = help: the following other types implement trait `bevy::prelude::Component`:
              AccessibilityNode
              bevy::prelude::Name
              bevy::prelude::GlobalTransform
              bevy::prelude::Transform
              PlaybackSettings
              bevy_winit::system::CachedWindow
              bevy::prelude::Children
              SpatialListener
            and 175 others
    = note: required for `TileBundle` to implement `DynamicBundle`
note: required by a bound in `component_ids`
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_ecs-0.13.0/src/bundle.rs:141:26
    |
141 | pub unsafe trait Bundle: DynamicBundle + Send + Sync + 'static {
    |                          ^^^^^^^^^^^^^ required by this bound in `Bundle::component_ids`
...
144 |     fn component_ids(
    |        ------------- required by a bound in this associated function

error[E0277]: the trait bound `TileBundle: bevy::prelude::Component` is not satisfied
   --> /Users/linonetwo/.cargo/git/checkouts/bevy_ecs_ldtk-a845ef6482ca980f/ef466f3/src/components/mod.rs:313:22
    |
313 |     pub tile_bundle: TileBundle,
    |                      ^^^^^^^^^^ the trait `bevy::prelude::Component` is not implemented for `TileBundle`
    |
    = help: the following other types implement trait `bevy::prelude::Component`:
              AccessibilityNode
              bevy::prelude::Name
              bevy::prelude::GlobalTransform
              bevy::prelude::Transform
              PlaybackSettings
              bevy_winit::system::CachedWindow
              bevy::prelude::Children
              SpatialListener
            and 175 others
    = note: required for `TileBundle` to implement `DynamicBundle`
note: required by a bound in `from_components`
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_ecs-0.13.0/src/bundle.rs:141:26
    |
141 | pub unsafe trait Bundle: DynamicBundle + Send + Sync + 'static {
    |                          ^^^^^^^^^^^^^ required by this bound in `Bundle::from_components`
...
157 |     unsafe fn from_components<T, F>(ctx: &mut T, func: &mut F) -> Self
    |               --------------- required by a bound in this associated function

error[E0599]: the method `get_components` exists for struct `TileBundle`, but its trait bounds were not satisfied
   --> /Users/linonetwo/.cargo/git/checkouts/bevy_ecs_ldtk-a845ef6482ca980f/ef466f3/src/components/mod.rs:311:39
    |
311 | #[derive(Copy, Clone, Debug, Default, Bundle)]
    |                                       ^^^^^^ method cannot be called on `TileBundle` due to unsatisfied trait bounds
    |
   ::: /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_ecs_tilemap-0.12.0/src/tiles/mod.rs:108:1
    |
108 | pub struct TileBundle {
    | ---------------------
    | |
    | doesn't satisfy `TileBundle: DynamicBundle`
    | doesn't satisfy `TileBundle: bevy::prelude::Component`
    |
    = note: the following trait bounds were not satisfied:
            `TileBundle: bevy::prelude::Component`
            which is required by `TileBundle: DynamicBundle`
            `&TileBundle: bevy::prelude::Component`
            which is required by `&TileBundle: DynamicBundle`
            `&mut TileBundle: bevy::prelude::Component`
            which is required by `&mut TileBundle: DynamicBundle`
    = help: items from traits can only be used if the trait is in scope
    = note: this error originates in the derive macro `Bundle` (in Nightly builds, run with -Z macro-backtrace for more info)
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
2   + use bevy_ecs::bundle::DynamicBundle;
    |

error[E0308]: mismatched types
   --> /Users/linonetwo/.cargo/git/checkouts/bevy_ecs_ldtk-a845ef6482ca980f/ef466f3/src/level.rs:157:33
    |
157 |                 commands.entity(tile_entity).insert(spatial_bundle);
    |                          ------ ^^^^^^^^^^^ expected `bevy::prelude::Entity`, found `bevy_ecs::entity::Entity`
    |                          |
    |                          arguments to this method are incorrect
    |
    = note: `bevy_ecs::entity::Entity` and `bevy::prelude::Entity` have similar names, but are actually distinct types
note: `bevy_ecs::entity::Entity` is defined in crate `bevy_ecs`
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_ecs-0.12.1/src/entity/mod.rs:119:1
    |
119 | pub struct Entity {
    | ^^^^^^^^^^^^^^^^^
note: `bevy::prelude::Entity` is defined in crate `bevy_ecs`
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_ecs-0.13.0/src/entity/mod.rs:139:1
    |
139 | pub struct Entity {
    | ^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `bevy_ecs` are being used?
note: method defined here
   --> /Users/linonetwo/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bevy_ecs-0.13.0/src/system/commands/mod.rs:338:12
    |
338 |     pub fn entity(&mut self, entity: Entity) -> EntityCommands {
    |            ^^^^^^

error[E0308]: mismatched types
   --> /Users/linonetwo/.cargo/git/checkouts/bevy_ecs_ldtk-a845ef6482ca980f/ef466f3/src/level.rs:158:33
    |
158 |                 commands.entity(tilemap_id.0).add_child(tile_entity);
    |                          ------ ^^^^^^^^^^^^ expected `bevy::prelude::Entity`, found `bevy_ecs::entity::Entity`
    |                          |
    |                          arguments to this method are incorrect
    |
    = note: `bevy_ecs::entity::Entity` and `bevy::prelude::Entity` have similar names, but are actually distinct types
note: `bevy_ecs::entity::Entity` is defined in crate `bevy_ecs`
   --> /Users/l [...]

2024-03-13 19:35 UTC, neocturne commented
@linonetwo Your `[dependencies]` entry for bevy_ecs_tilemap must match the one in bevy_ecs_ldtk (`bevy_ecs_tilemap = "0.12"`) to allow cargo to unify them (or you can omit it altogether if your crate does not use bevy_ecs_tilemap directly).

Use the `[patch.crates-io]` section to override that dependency to use the current git version:
```
[patch.crates-io]
bevy_ecs_tilemap = { git = "https://github.com/StarArawn/bevy_ecs_tilemap" }
```

2024-03-13 23:32 UTC, theshortcut commented
yep looks like the PR merged but we'd still need a release of bevy_ecs_tilemap cut to be able to bump the dependency here and release a version of bevy_ecs_ldtk. I'll mark this PR as ready for review anyway and keep an eye on crate releases.

2024-03-26 05:29 UTC, Trouv requested changes
Thanks a lot for taking this off my plate. Here's a couple small comments. I need to figure out why CI isn't running and try out the examples next

2024-03-26 05:29 UTC, Trouv commented on Cargo.toml
> +bevy_ecs_tilemap = { git = "https://github.com/rparrett/bevy_ecs_tilemap/", branch = "bevy13" }
This could be updated to `main` now
```suggestion
bevy_ecs_tilemap = { git = "https://github.com/rparrett/bevy_ecs_tilemap/", branch = "main" }
```

2024-03-26 05:29 UTC, Trouv commented on Cargo.toml
> +bevy_ecs_tilemap = { git = "https://github.com/rparrett/bevy_ecs_tilemap/", branch = "bevy13" }
So I'm actually happy to merge this (assuming the examples are fine after I check them and the CI passes) before `bevy_ecs_tilemap` 0.13. However, I do ask that a new line is added to the compatibility chart in the `README.md` w/ `bevy_ecs_tilemap` and `bevy_ecs_ldtk` set to `main`.

2024-03-27 16:42 UTC, theshortcut commented
@Trouv I've updated the cargo patch definition to pull from upstream main branch instead of the PR branch and the compat table in the readme.

2024-03-28 02:42 UTC, Trouv commented
It seems that your last push allowed me to run the CI. It's passing but the "Build and test book" job is actually secretly failing (see #270).
```
 - Test: how-to-guides/respawn-levels-and-worlds.md_sect_respawn_the_currently_selected_level_line_76 (Failed to compile)
 - Test: how-to-guides/respawn-levels-and-worlds.md_sect_respawn_the_currently_selected_level_line_32 (Failed to compile)
```
Those md files are in the `book/src` directory. I think it's just Input -> ButtonInput and KeyCode::L -> KeyCode::KeyL changes

2024-03-28 19:18 UTC, theshortcut commented
Updated and locally ran mdbook which passes the mdbook-keeper tests for me. Will check the CI build when that goes too thanks for catching that.

2024-04-02 05:41 UTC, Trouv approved these changes
LGTM, and I've verified the examples are working as expected. Thanks again!

2024-04-02 05:42 UTC, merged